### ISSUE TITLE
overlapping page logo in the navigation (too many tabs/li items)

### ISSUE THREAD

**Issue by adeliktas** [hughbris/grav-theme-minimaxing#13]
When there are too many or too long page (li block) items, it gets pushed to the left overlapping the page logo. It would be great if it instead creates a second row for navigation tabs or any other solution.

![aadsfsaf](https://user-images.githubusercontent.com/64136642/84785011-418a9d00-afeb-11ea-8295-aec6b2b29cb7.png)

Thanks in advance!

somewhat similar to https://github.com/hughbris/grav-theme-minimaxing/issues/12

**Comment by Allamaris0** [comment]
Try:
```
	#header {
                background-color: #007b9d;
		background-image: -moz-linear-gradient(top, #008ead, #007b9d);
		background-image: -webkit-linear-gradient(top, #008ead, #007b9d);
		background-image: -ms-linear-gradient(top, #008ead, #007b9d);
		background-image: linear-gradient(top, #008ead, #007b9d);
		-moz-box-sizing: content-box;
		-webkit-box-sizing: content-box;
		-ms-box-sizing: content-box;
		box-sizing: content-box;
		position: relative;
		margin: 2.5% 0 2.5% 0;
		padding: 0 40px 0 40px;
		border-radius: 10px;
		border: solid 1px #006e8b;
		box-shadow: inset 0px 0px 0px 1px #12a0bf, 0px 1px 4px 0px rgba(0, 0, 0, 0.1);
		min-height: 86px;
                display: flex;
                align-items: center;
			}
```

				#header h1 {
					color: #fff;
					font-size: 2.4em;
					letter-spacing: -2px;
					padding: 0 50px 0 10px;
				}

					#header h1 a {
						color: #fff;
						text-decoration: none;
					}

				#header nav {
					line-height: 84px;
					text-transform: lowercase;
					font-size: 1.3em;
					letter-spacing: -1px;
				}
                    #header nav ul {
                        padding: 0;
                    }

                    #header nav li {
                        display: block;
                        float: left;
			outline: 0;
                        position: relative;
                    }
                    
			#header nav a {
                        	text-decoration: none;
				color: #fff;
				padding: 0 25px 0 25px;
				outline: 0;
			}


It should look like this
![grav-header](https://user-images.githubusercontent.com/51059882/84825022-16bb3b80-b021-11ea-900d-bdf344df1539.JPG)

If it's not what you expect, then you can wrote to me on Discord (Adamantine#0458). I'm not a front-end developer and definitely I'm not good at UX stuff, but I can try to help you.

**Comment by adeliktas** [comment]
thanks that's a great help solving this issue!
I adjusted some parts for my needs
```
text-transform: lowercase; => text-transform: none;
#header {//padding: 0 40px 0 40px;
#header nav li {//https://stackoverflow.com/questions/13745347/make-whole-li-as-link-with-proper-html
display: block;
float: left;
outline: 0;
position: relative;
//display: inline-block
}

#header nav a {
display: block;
text-decoration: none;
color: #fff;
padding: 0 25px 0 25px;
outline: 0;
}
```

As of Design it would be nice if the logo stays in the first line and doesnt adjust in postition/height(without padding) when there is another row of menu

Example:
![asffasfasfsaf](https://user-images.githubusercontent.com/64136642/84832108-ed081180-b02c-11ea-8d70-fa10543f3f6f.png)

**Comment by Allamaris0** [comment]
Just delete `align-items: center;` and you can add some padding-top for #header h1

**Comment by adeliktas** [comment]
Solved thanks again to @Allamaris0
